version: "2"
services:
  wp:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp
    links:
      - db
    ports:
      - 80:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
  db:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
    volumes:
      - ./db:/docker-entrypoint-initdb.d